# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Tom/Desktop/RC_CAR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Tom/Desktop/RC_CAR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Tom/Desktop/RC_CAR/CMakeFiles /Users/Tom/Desktop/RC_CAR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Tom/Desktop/RC_CAR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

controls.o: controls.cpp.o

.PHONY : controls.o

# target to build an object file
controls.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/controls.cpp.o
.PHONY : controls.cpp.o

controls.i: controls.cpp.i

.PHONY : controls.i

# target to preprocess a source file
controls.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/controls.cpp.i
.PHONY : controls.cpp.i

controls.s: controls.cpp.s

.PHONY : controls.s

# target to generate assembly for a file
controls.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/controls.cpp.s
.PHONY : controls.cpp.s

libs/PCA9685.o: libs/PCA9685.cpp.o

.PHONY : libs/PCA9685.o

# target to build an object file
libs/PCA9685.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/PCA9685.cpp.o
.PHONY : libs/PCA9685.cpp.o

libs/PCA9685.i: libs/PCA9685.cpp.i

.PHONY : libs/PCA9685.i

# target to preprocess a source file
libs/PCA9685.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/PCA9685.cpp.i
.PHONY : libs/PCA9685.cpp.i

libs/PCA9685.s: libs/PCA9685.cpp.s

.PHONY : libs/PCA9685.s

# target to generate assembly for a file
libs/PCA9685.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/PCA9685.cpp.s
.PHONY : libs/PCA9685.cpp.s

libs/camera.o: libs/camera.cpp.o

.PHONY : libs/camera.o

# target to build an object file
libs/camera.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/camera.cpp.o
.PHONY : libs/camera.cpp.o

libs/camera.i: libs/camera.cpp.i

.PHONY : libs/camera.i

# target to preprocess a source file
libs/camera.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/camera.cpp.i
.PHONY : libs/camera.cpp.i

libs/camera.s: libs/camera.cpp.s

.PHONY : libs/camera.s

# target to generate assembly for a file
libs/camera.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/libs/camera.cpp.s
.PHONY : libs/camera.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run"
	@echo "... controls.o"
	@echo "... controls.i"
	@echo "... controls.s"
	@echo "... libs/PCA9685.o"
	@echo "... libs/PCA9685.i"
	@echo "... libs/PCA9685.s"
	@echo "... libs/camera.o"
	@echo "... libs/camera.i"
	@echo "... libs/camera.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

